# Generated by Django 5.0.1 on 2024-02-05 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicapp', '0002_editablecontent_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditableContent',
            new_name='mission',
        ),
    ]
