# Generated by Django 5.0.1 on 2024-02-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicapp', '0003_rename_editablecontent_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcontent', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
