# Generated by Django 5.0.1 on 2024-02-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicapp', '0007_pic1'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abtcontent', models.TextField()),
            ],
        ),
    ]
