# Generated by Django 5.0.1 on 2024-02-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicapp', '0008_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='whatsets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wscontent', models.TextField()),
            ],
        ),
    ]
