# Generated by Django 5.0.1 on 2024-02-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicapp', '0009_whatsets'),
    ]

    operations = [
        migrations.CreateModel(
            name='post1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1content', models.TextField()),
            ],
        ),
    ]
