# Generated by Django 5.0.1 on 2024-02-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicapp', '0011_post2_post3'),
    ]

    operations = [
        migrations.CreateModel(
            name='obj1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj1content', models.TextField()),
            ],
        ),
    ]
